In [ ]:
import numpy as np
import mesh
import forwardProblem
import inverseProblem
import inverseProblem_2D
import matplotlib.pyplot as plt

## Regularização Filtro Gaussiano FP_Alta

fonte: Erick equação C.37

$$
\hat{\theta}_{k+1} = \hat{\theta}_k + \alpha_k
\left( J_k^T W_1 J_k + \lambda^2 L_2^T L_2 \right)^{-1}
\cdot \left( J_k^T W_1 (z - h(\hat{\theta}_k)) - \lambda^2 L_2^T L_2 (\hat{\theta}_k - \theta^*) \right)
$$
onde,
$$W_1=L_1^T L_1$$

# TESTE ANISOTRÓPICO com eletrodo pontual 

In [1]:
import numpy as np
import mesh
import forwardProblem
import inverseProblem
import inverseProblem_2D
import matplotlib.pyplot as plt

# TESTE COM eletrodo pontual mesh 4 elementos

###############################################################################
nome = '../../malhasMSH/quatro_triangulos_03nov2025.msh'
#nome = '../../malhasMSH/dezesseis_triangulos_22jan25.msh'
#nome = '../../malhasMSH/circ16_base_plus.msh'
#nome = '../../malhasMSH/fantomaAnisotropia01.msh'
#nome = '../../malhasMSH/quadrado_16e.msh'
#nome = '../../malhasMSH/dezesseis_triangulos_1body.msh'
#nome = '../../malhasMSH/quadrado_16e_plus.msh'
#nome = '../../malhasMSH/quatro_4e_em_XY.msh'

#MinhaMalhaPto2 = mesh.PointElectrodes2DMeshEdson(4, nome_msh=nome, altura2D = 1.00)
MinhaMalhaPto2 = mesh.PointElectrodes2DMeshAnisotropic(4, nome_msh=nome, altura2D = 0.02, thetaAngle = -45.0)
#MinhaMalhaPto2 = mesh.PointElectrodes2DMeshEdson(4, nome_msh=nome, altura2D = 0.02, useEdson=True)

#LinearTriangleAnisotropic
MinhaMalhaPto2.ReadMesh() 

#print(MinhaMalhaPto2.Elements[2])
#print(f"Centroid: {MinhaMalhaPto2.Elements[2].Centroid}")
#print(f"KGeo: \n{MinhaMalhaPto2.Elements[2].KGeo}")
#sigma_inicial = np.full(MinhaMalhaPto2.NumberOfElements, 1.0)          # Monta vetor sigma inicial


'''
meus_sigmas = {
1000 : 1.000}#,
#1001 : 10.00}#,
#1002 : 2.00,    
#1003 : 2.00}

meus_sigmas = {
1000 : 1.0,
1001 : 1.0,
10000 : 1.0e9,
10001 : 1.0e9,
10002 : 1.0e9,
10003 : 1.0e9, 
10004 : 1.0e9,     
}
'''
meus_sigmas = {
    1000: {"sigma_xx": 3.0, "sigma_xy": 0.2, "sigma_yy": 1.0}}#,
#    1001: {"sigma_xx": 1.0, "sigma_xy": 0.0, "sigma_yy": 1.0},
#    5001: {"sigma_xx": 10.0, "sigma_xy": 0.0, "sigma_yy": 0.1},
#}
#meus_sigmas= np.loadtxt("fantomaAnisotropiaSigma.txt")


MinhaMalhaPto2.SetSigmaPhysicaEntity(meus_sigmas)
#MinhaMalhaPto2.SetSigmaElements(meus_sigmas)
'''
MinhaMalhaPto2.CalcKGlobal() # calculando KGlobal usando Sigmas

print('meus_sigmas',meus_sigmas)
#print(f'MinhaMalhaPto2.KGlobal =  {MinhaMalhaPto2.KGlobal}')

fwd = forwardProblem.forward_problem(MinhaMalhaPto2, Pcorrente=None, SkipPattern=1, I =1.0e-3)   # __init__ roda aqui

#print(f'Pcorrente \n {fwd.corrente[MinhaMalhaPto.NumberOfNodes-MinhaMalhaPto.NumberOfElectrodes: MinhaMalhaPto.NumberOfNodes]}')
#print(f'Pcorrente \n {fwd.corrente[:16]}')

#print(f'Pcorrente \n {fwd.corrente.shape}')

mtz_Vmedido = fwd.Solve()
#print(f'Vmedido \n {fwd.Vmedido[:,0]}')

nome_arquivo = 'ParaVernoGmshPto'
fwd.criar_arquivo_pos_2D( fwd.Vmedido, nome_arquivo)

fwd.abrir_Gmsh_pos(nome_arquivo, runGmsh=True)

#print(f'self.Yinversa \n {fwd.Yinversa}')

V_measured = fwd.Vmedido_eletrodos
#print('V_measured ',V_measured)
print('meus_sigmas ',meus_sigmas)
'''

Reading ../../malhasMSH/quatro_triangulos_03nov2025.msh.

msh_physical_groups found (type triangle): [1000 1000 1000 1000].
Physical tags found: [1000].
Physical tags points: [10000 10001 10002 10003 10004]
4 electrodes found.
MSH file with 4 elements and 5 nodes.
ElectrodeNodes: [0 1 2 3]
GndNode: 4
Physical tag: 1.0 1.0
1.0000000000000002 0.0 1.0000000000000002
Physical tag: 1.0 1.0
1.0000000000000002 0.0 1.0000000000000002
Physical tag: 1.0 1.0
1.0000000000000002 0.0 1.0000000000000002
Physical tag: 1.0 1.0
1.0000000000000002 0.0 1.0000000000000002
self.sigma_vec 11111: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
tag 11111: 1000
sigma_value 11111: {'sigma_xx': 3.0, 'sigma_xy': 0.2, 'sigma_yy': 1.0}


AttributeError: 'LinearTriangleAnisotropic' object has no attribute 'SetSigma'