In [49]:
import numpy as np
import mesh

# EXEMPLOS BIBLIOTECA EDSON

ToDo:

- Implementar elemento 1D ( class LinearLineEdson() ) [elements.py]
- Implementar malha 1D ( class PointElectrodes1DMeshEdson() ) [mesh.py]
- Rodar exemplos 1D antigos e ver se bate
- Implementar problema direto (que deve funcionar com qualquer malha, não interessa se é 1D, 2D, com ou sem eletrodo...) [forward.py]

## Teste Tarefa unidimensional 
(class PointElectrodes1DMeshEdson()).

In [50]:
nome = '../../malhasMSH/unidimensional_100e_py.msh'

MinhaMalha1D = mesh.PointElectrodes1DMeshEdson(2, nome_msh=nome, altura1D = 0.02)
MinhaMalha1D.ReadMesh()

Reading ../../malhasMSH/unidimensional_100e_py.msh.

msh_physical_groups found (type line): [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2].
Physical tags found (type line): [1 2].
2 electrodes found.
MSH file with 100 elements and 101 nodes.
GndNode: 0
first five coordinates: [[0.   0.   0.  ]
 [0.01 0.   0.  ]
 [0.02 0.   0.  ]
 [0.03 0.   0.  ]
 [0.04 0.   0.  ]]
Altura1D: 0.02


## Comparação malhas sem eletrodo

In [51]:
nome = '../../malhasMSH/circ16_anomalia6.msh'
MinhaMalhaEdson = mesh.PointElectrodes2DMeshEdson(16, nome_msh=nome, altura2D = 0.02, useEdson=True)
MinhaMalhaErick = mesh.PointElectrodes2DMeshEdson(16, nome_msh=nome, altura2D = 0.02, useEdson=False)

MinhaMalhaEdson.ReadMesh()
MinhaMalhaErick.ReadMesh()

Reading ../../malhasMSH/circ16_anomalia6.msh.

Physical tags found: [1000 1001].
452 Elements and 257 Nodes found.
ElectrodeNodes: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
GndNode: 16
72 174 176
KGeo1 [[ 0.00963852 -0.00347946 -0.00615906]
 [-0.00347946  0.0116311  -0.00815165]
 [-0.00615906 -0.00815165  0.01431071]]
174 72 220
KGeo1 [[ 0.0094074  -0.00144861 -0.0079588 ]
 [-0.00144861  0.01085299 -0.00940438]
 [-0.0079588  -0.00940438  0.01736318]]
28 3 209
KGeo1 [[ 0.01283178 -0.00815473 -0.00467705]
 [-0.00815473  0.01297557 -0.00482084]
 [-0.00467705 -0.00482084  0.00949788]]
144 145 211
KGeo1 [[ 0.01544091 -0.00672045 -0.00872046]
 [-0.00672045  0.00940128 -0.00268084]
 [-0.00872046 -0.00268084  0.0114013 ]]
11 45 206
KGeo1 [[ 0.01191827 -0.00758951 -0.00432875]
 [-0.00758951  0.01322346 -0.00563395]
 [-0.00432875 -0.00563395  0.0099627 ]]
132 214 219
KGeo1 [[ 0.01219612 -0.00638895 -0.00580716]
 [-0.00638895  0.01154619 -0.00515724]
 [-0.00580716 -0.00515724  0.0109644 ]

In [52]:
MinhaMalhaEdson.SetRhoValue(10)
MinhaMalhaEdson.CalcKGlobal()

MinhaMalhaErick.SetRhoValue(10)
MinhaMalhaErick.CalcKGlobal()

 elemento_0 [ 72 174 176]
 elemento_1 [174  72 220]
 elemento_2 [ 28   3 209]
 elemento_3 [144 145 211]
 elemento_4 [ 11  45 206]
 elemento_5 [132 214 219]
 elemento_6 [110 119 208]
 elemento_7 [145  78 211]
 elemento_8 [  6  35 216]
 elemento_9 [119 129 141]
 elemento_10 [ 75 160 161]
 elemento_11 [141 129 142]
 elemento_12 [ 15  53 211]
 elemento_13 [160  75 162]
 elemento_14 [ 36   7 220]
 elemento_15 [119 141 208]
 elemento_16 [144  93 171]
 elemento_17 [ 41  42 191]
 elemento_18 [113 138 140]
 elemento_19 [170  77 196]
 elemento_20 [113 140 146]
 elemento_21 [ 76  11 206]
 elemento_22 [ 93 144 211]
 elemento_23 [ 77 170 229]
 elemento_24 [144 142 145]
 elemento_25 [175  96 224]
 elemento_26 [214  67 219]
 elemento_27 [  3 117 209]
 elemento_28 [ 96 175 220]
 elemento_29 [212 175 224]
 elemento_30 [175 174 220]
 elemento_31 [  2  27 189]
 elemento_32 [188  16 213]
 elemento_33 [ 28 209 227]
 elemento_34 [ 42  69 191]
 elemento_35 [ 16 188 243]
 elemento_36 [116   6 216]
 elemento_3

In [53]:
print(MinhaMalhaEdson.KGlobal[0:10,0:10])
print(MinhaMalhaErick.KGlobal[0:10,0:10])

[[0.00329627 0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.00362387 0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.00354618 0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.00339305 0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.00329332 0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.00346789
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.00330776 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.00336434 0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.00330704 0.        ]
 [0.         0.         0.   

In [54]:
MinhaMalhaEdson.KGlobal.shape

(257, 257)

In [55]:
for linha in range(257):
    dif =  np.max(np.abs(MinhaMalhaEdson.KGlobal[linha]-MinhaMalhaErick.KGlobal[linha]))
    if dif > 1e-7:
        print(f'linha {linha}: {dif}')

print(f'Erro maximo: {np.max(np.abs(MinhaMalhaEdson.KGlobal-MinhaMalhaErick.KGlobal))}')

Erro maximo: 8.673617379884035e-19


In [56]:
MinhaMalhaEdson.Elements[0].KGeo

array([[ 0.00963852, -0.00347946, -0.00615906],
       [-0.00347946,  0.0116311 , -0.00815165],
       [-0.00615906, -0.00815165,  0.01431071]])

In [57]:
MinhaMalhaErick.Elements[0].KGeo

array([[ 0.00963852, -0.00347946, -0.00615906],
       [-0.00347946,  0.0116311 , -0.00815165],
       [-0.00615906, -0.00815165,  0.01431071]])

PARA EDSON: Tem uma diferença na linha 2, coluna 3... (e na linha 3, coluna 2, pela simetria)... encontrar quem está errado!!!!

In [58]:
print(MinhaMalhaEdson.Elements[1].KGeo)
print(MinhaMalhaErick.Elements[1].KGeo)

[[ 0.0094074  -0.00144861 -0.0079588 ]
 [-0.00144861  0.01085299 -0.00940438]
 [-0.0079588  -0.00940438  0.01736318]]
[[ 0.0094074  -0.00144861 -0.0079588 ]
 [-0.00144861  0.01085299 -0.00940438]
 [-0.0079588  -0.00940438  0.01736318]]


## Testes com HUA

In [59]:
nome = '../../malhasMSH/circ2_tst_Hua_v2_2_lc_especial.msh'
#nome = '../../malhasMSH/circ8_anom4_tst_Hua_v2_2_lc_especial.msh'

MinhaMalha = mesh.HuaElectrodes2DMeshEdson(2, nome_msh=nome, altura2D = 0.02)
MinhaMalha.ReadMesh() 

Reading ../../malhasMSH/circ2_tst_Hua_v2_2_lc_especial.msh.

msh_physical_groups found (type triangle): [1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000
 1000 1000 1000 1000].
Physical tags found (type triangle): [1000].
Physical tags: lines: [5001 5002]; points: [10000]
2 electrodes found.
MSH file with 18 elements and 17 nodes.
ElectrodeNodes: [17 18]
26 Elements and 19 Nodes found on model.
GndNode: 10


In [60]:
print(MinhaMalha.KGlobal)

None


In [61]:
print(MinhaMalha.Elements[2])
print(f"Centroid: {MinhaMalha.Elements[2].Centroid}")
print(f"KGeo: \n{MinhaMalha.Elements[2].KGeo}")

Centroid: [ 0.11114379 -0.04717695  0.        ]
KGeo: 
[[ 0.00286201  0.00035101 -0.00321302]
 [ 0.00035101  0.03498348 -0.03533448]
 [-0.00321302 -0.03533448  0.0385475 ]]


In [62]:
meus_sigmas = {}
meus_sigmas[1000] = 0.1
meus_sigmas[5001] = 0.2
meus_sigmas[5002] = 0.2
MinhaMalha.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)

MinhaMalha.CalcKGlobal() # calculando KGlobal usando Sigmas

MinhaMalha.KGlobal




KGlobal =  MinhaMalha.KGlobal

print('KGlobal', KGlobal[17])

CHAVES recebidas em dic: [1000, 5001, 5002]
 elemento_0 [ 4 11 16]
 elemento_1 [ 9 13 15]
 elemento_2 [14  0 16]
 elemento_3 [12  5 15]
 elemento_4 [ 8  9 15]
 elemento_5 [ 3  4 16]
 elemento_6 [ 5  6 15]
 elemento_7 [ 0  1 16]
 elemento_8 [10 11 12]
 elemento_9 [14 10 13]
 elemento_10 [11 10 16]
 elemento_11 [13 10 15]
 elemento_12 [10 12 15]
 elemento_13 [10 14 16]
 elemento_14 [ 1  2 16]
 elemento_15 [ 2  3 16]
 elemento_16 [ 6  7 15]
 elemento_17 [ 7  8 15]
 elemento_18 [ 0  1 17]
 elemento_19 [ 1  2 17]
 elemento_20 [ 2  3 17]
 elemento_21 [ 3  4 17]
 elemento_22 [ 5  6 18]
 elemento_23 [ 6  7 18]
 elemento_24 [ 7  8 18]
 elemento_25 [ 8  9 18]
KGlobal [-9.99953704e-06 -1.99990741e-05 -1.99990741e-05 -1.99990741e-05
 -9.99953704e-06  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  7.99962963e-05  0.00000000e+00]


In [63]:
'''
meus_sigmas = {}
meus_sigmas[1000] = 0.1
#meus_sigmas[2] = 0.2
MinhaMalha.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)
'''

'\nmeus_sigmas = {}\nmeus_sigmas[1000] = 0.1\n#meus_sigmas[2] = 0.2\nMinhaMalha.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)\n'

In [64]:
#MinhaMalha.CalcKGlobal() # calculando KGlobal usando Sigmas

In [65]:
#MinhaMalha.KGlobal

# EXEMPLOS BIBLIOTECAS OLD

In [66]:
'''
nome = '../../malhasMSH/circ8_anomalia5.msh'

MinhaMalha = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
MinhaMalha.ReadMesh()
'''

"\nnome = '../../malhasMSH/circ8_anomalia5.msh'\n\nMinhaMalha = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)\nMinhaMalha.ReadMesh()\n"

In [67]:
'''
print(MinhaMalha.Elements[2])
print(f"Centroid: {MinhaMalha.Elements[2].Centroid}")
print(f"KGeo: \n{MinhaMalha.Elements[2].KGeo}")
'''

'\nprint(MinhaMalha.Elements[2])\nprint(f"Centroid: {MinhaMalha.Elements[2].Centroid}")\nprint(f"KGeo: \n{MinhaMalha.Elements[2].KGeo}")\n'

In [68]:
'''
meus_sigmas = {}
meus_sigmas[1] = 0.1
meus_sigmas[2] = 0.2
MinhaMalha.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)
'''

'\nmeus_sigmas = {}\nmeus_sigmas[1] = 0.1\nmeus_sigmas[2] = 0.2\nMinhaMalha.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)\n'

In [69]:
#MinhaMalha.CalcKGlobal() # calculando KGlobal usando Sigmas

In [70]:
#MinhaMalha.KGlobal

In [71]:
'''
M2 = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
M2.ReadMesh()
meus_rhos = {}
meus_rhos[1] = 10
meus_rhos[2] = 5
M2.SetRhoPhysicaEntity(meus_rhos) # Informando rho (e já calculando o sigma de cada elemento)
M2.CalcKGlobal() # calculando KGlobal usando Sigmas
M2.KGlobal
'''

'\nM2 = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)\nM2.ReadMesh()\nmeus_rhos = {}\nmeus_rhos[1] = 10\nmeus_rhos[2] = 5\nM2.SetRhoPhysicaEntity(meus_rhos) # Informando rho (e já calculando o sigma de cada elemento)\nM2.CalcKGlobal() # calculando KGlobal usando Sigmas\nM2.KGlobal\n'

In [72]:
'''
M3 = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
M3.ReadMesh()
meus_rhos = {}
meus_rhos[1] = 10
meus_rhos[2] = 5
M3.SetRhoPhysicaEntity(meus_rhos) # Informando rho (e já calculando o sigma de cada elemento)
M3.FlagRhoBased = True
M3.CalcKGlobal() # calculando KGlobal usando Rho
M3.KGlobal
'''

'\nM3 = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)\nM3.ReadMesh()\nmeus_rhos = {}\nmeus_rhos[1] = 10\nmeus_rhos[2] = 5\nM3.SetRhoPhysicaEntity(meus_rhos) # Informando rho (e já calculando o sigma de cada elemento)\nM3.FlagRhoBased = True\nM3.CalcKGlobal() # calculando KGlobal usando Rho\nM3.KGlobal\n'

In [73]:
'''
M4 = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
M4.ReadMesh()
meus_sigmas = {}
meus_sigmas[1] = 0.1
meus_sigmas[2] = 0.2
M4.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)
M4.FlagRhoBased = True
M4.CalcKGlobal() # calculando KGlobal usando Rho
M4.KGlobal
'''

'\nM4 = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)\nM4.ReadMesh()\nmeus_sigmas = {}\nmeus_sigmas[1] = 0.1\nmeus_sigmas[2] = 0.2\nM4.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)\nM4.FlagRhoBased = True\nM4.CalcKGlobal() # calculando KGlobal usando Rho\nM4.KGlobal\n'

In [74]:
# M4

Comparação ajustando por valores, physical grous ou vetores

In [75]:
'''
Mpg = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
Mpg.ReadMesh()
meus_sigmas = {}
meus_sigmas[1] = 0.1
meus_sigmas[2] = 0.1
Mpg.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)
Mpg.FlagRhoBased = True
Mpg.CalcKGlobal() # calculando KGlobal usando Rho
Mpg.KGlobal
'''

'\nMpg = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)\nMpg.ReadMesh()\nmeus_sigmas = {}\nmeus_sigmas[1] = 0.1\nmeus_sigmas[2] = 0.1\nMpg.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)\nMpg.FlagRhoBased = True\nMpg.CalcKGlobal() # calculando KGlobal usando Rho\nMpg.KGlobal\n'

In [76]:
'''
Mval = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
Mval.ReadMesh()
value = 0.1
Mval.SetSigmaValue(value) # Informando sigma (e já calculando o rho de cada elemento)
Mval.FlagRhoBased = True
Mval.CalcKGlobal() # calculando KGlobal usando Rho
Mval.KGlobal
'''

'\nMval = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)\nMval.ReadMesh()\nvalue = 0.1\nMval.SetSigmaValue(value) # Informando sigma (e já calculando o rho de cada elemento)\nMval.FlagRhoBased = True\nMval.CalcKGlobal() # calculando KGlobal usando Rho\nMval.KGlobal\n'

In [77]:
'''
Mvec = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
Mvec.ReadMesh()
vec = np.ones(Mvec.NumberOfElements) * 0.1
Mvec.SetSigmaElements(vec) # Informando sigma (e já calculando o rho de cada elemento)
Mvec.FlagRhoBased = True
Mvec.CalcKGlobal() # calculando KGlobal usando Rho
Mvec.KGlobal
'''

'\nMvec = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)\nMvec.ReadMesh()\nvec = np.ones(Mvec.NumberOfElements) * 0.1\nMvec.SetSigmaElements(vec) # Informando sigma (e já calculando o rho de cada elemento)\nMvec.FlagRhoBased = True\nMvec.CalcKGlobal() # calculando KGlobal usando Rho\nMvec.KGlobal\n'