In [19]:
import numpy as np
import mesh

In [2]:
nome = '../../malhasMSH/circ8_anomalia5.msh'

MinhaMalha = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
MinhaMalha.ReadMesh()

Reading ../../malhasMSH/circ8_anomalia5.msh.

Physical tags found: [1 2].
534 Elements and 302 Nodes found.
ElectrodeNodes: [0 1 2 3 4 5 6 7]
GndNode: 8


In [3]:
print(MinhaMalha.Elements[2])
print(f"Centroid: {MinhaMalha.Elements[2].Centroid}")
print(f"KGeo: \n{MinhaMalha.Elements[2].KGeo}")

Centroid: [0.01809848 0.005433   0.        ]
KGeo: 
[[ 0.00902397 -0.00622189 -0.00280208]
 [-0.00622189  0.0153715  -0.00914961]
 [-0.00280208 -0.00914961  0.01195169]]


In [ ]:
meus_sigmas = {}
meus_sigmas[1] = 0.1
meus_sigmas[2] = 0.2
MinhaMalha.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)

In [ ]:
MinhaMalha.CalcKGlobal() # calculando KGlobal usando Sigmas

In [7]:
MinhaMalha.KGlobal

array([[ 0.00339063,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.00343123,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00329807, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.01399727,
        -0.00143557, -0.00309086],
       [ 0.        ,  0.        ,  0.        , ..., -0.00143557,
         0.01413989, -0.00237716],
       [ 0.        ,  0.        ,  0.        , ..., -0.00309086,
        -0.00237716,  0.01463042]], shape=(302, 302))

In [ ]:
M2 = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
M2.ReadMesh()
meus_rhos = {}
meus_rhos[1] = 10
meus_rhos[2] = 5
M2.SetRhoPhysicaEntity(meus_rhos) # Informando rho (e já calculando o sigma de cada elemento)
M2.CalcKGlobal() # calculando KGlobal usando Sigmas
M2.KGlobal

Reading ../../malhasMSH/circ8_anomalia5.msh.

Physical tags found: [1 2].
534 Elements and 302 Nodes found.
ElectrodeNodes: [0 1 2 3 4 5 6 7]
GndNode: 8


array([[ 0.00339063,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.00343123,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00329807, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.01399727,
        -0.00143557, -0.00309086],
       [ 0.        ,  0.        ,  0.        , ..., -0.00143557,
         0.01413989, -0.00237716],
       [ 0.        ,  0.        ,  0.        , ..., -0.00309086,
        -0.00237716,  0.01463042]], shape=(302, 302))

In [15]:
M3 = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
M3.ReadMesh()
meus_rhos = {}
meus_rhos[1] = 10
meus_rhos[2] = 5
M3.SetRhoPhysicaEntity(meus_rhos) # Informando rho (e já calculando o sigma de cada elemento)
M3.FlagRhoBased = True
M3.CalcKGlobal() # calculando KGlobal usando Rho
M3.KGlobal

Reading ../../malhasMSH/circ8_anomalia5.msh.

Physical tags found: [1 2].
534 Elements and 302 Nodes found.
ElectrodeNodes: [0 1 2 3 4 5 6 7]
GndNode: 8


array([[ 0.00339063,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.00343123,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00329807, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.01399727,
        -0.00143557, -0.00309086],
       [ 0.        ,  0.        ,  0.        , ..., -0.00143557,
         0.01413989, -0.00237716],
       [ 0.        ,  0.        ,  0.        , ..., -0.00309086,
        -0.00237716,  0.01463042]], shape=(302, 302))

In [11]:
M4 = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
M4.ReadMesh()
meus_sigmas = {}
meus_sigmas[1] = 0.1
meus_sigmas[2] = 0.2
M4.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)
M4.FlagRhoBased = True
M4.CalcKGlobal() # calculando KGlobal usando Rho
M4.KGlobal

Reading ../../malhasMSH/circ8_anomalia5.msh.

Physical tags found: [1 2].
534 Elements and 302 Nodes found.
ElectrodeNodes: [0 1 2 3 4 5 6 7]
GndNode: 8


array([[ 0.00339063,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.00343123,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00329807, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.01399727,
        -0.00143557, -0.00309086],
       [ 0.        ,  0.        ,  0.        , ..., -0.00143557,
         0.01413989, -0.00237716],
       [ 0.        ,  0.        ,  0.        , ..., -0.00309086,
        -0.00237716,  0.01463042]], shape=(302, 302))

In [13]:
M4

Comparação ajustando por valores, physical grous ou vetores

In [16]:
Mpg = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
Mpg.ReadMesh()
meus_sigmas = {}
meus_sigmas[1] = 0.1
meus_sigmas[2] = 0.1
Mpg.SetSigmaPhysicaEntity(meus_sigmas) # Informando sigma (e já calculando o rho de cada elemento)
Mpg.FlagRhoBased = True
Mpg.CalcKGlobal() # calculando KGlobal usando Rho
Mpg.KGlobal

Reading ../../malhasMSH/circ8_anomalia5.msh.

Physical tags found: [1 2].
534 Elements and 302 Nodes found.
ElectrodeNodes: [0 1 2 3 4 5 6 7]
GndNode: 8


array([[ 0.00339063,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.00343123,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00329807, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.00699863,
        -0.00071779, -0.00154543],
       [ 0.        ,  0.        ,  0.        , ..., -0.00071779,
         0.00706994, -0.00118858],
       [ 0.        ,  0.        ,  0.        , ..., -0.00154543,
        -0.00118858,  0.00731521]], shape=(302, 302))

In [17]:
Mval = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
Mval.ReadMesh()
value = 0.1
Mval.SetSigmaValue(value) # Informando sigma (e já calculando o rho de cada elemento)
Mval.FlagRhoBased = True
Mval.CalcKGlobal() # calculando KGlobal usando Rho
Mval.KGlobal

Reading ../../malhasMSH/circ8_anomalia5.msh.

Physical tags found: [1 2].
534 Elements and 302 Nodes found.
ElectrodeNodes: [0 1 2 3 4 5 6 7]
GndNode: 8


array([[ 0.00339063,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.00343123,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00329807, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.00699863,
        -0.00071779, -0.00154543],
       [ 0.        ,  0.        ,  0.        , ..., -0.00071779,
         0.00706994, -0.00118858],
       [ 0.        ,  0.        ,  0.        , ..., -0.00154543,
        -0.00118858,  0.00731521]], shape=(302, 302))

In [20]:
Mvec = mesh.PointElectrodes2DMeshEdson(8, nome_msh=nome, altura2D = 0.02)
Mvec.ReadMesh()
vec = np.ones(Mvec.NumberOfElements) * 0.1
Mvec.SetSigmaElements(vec) # Informando sigma (e já calculando o rho de cada elemento)
Mvec.FlagRhoBased = True
Mvec.CalcKGlobal() # calculando KGlobal usando Rho
Mvec.KGlobal

Reading ../../malhasMSH/circ8_anomalia5.msh.

Physical tags found: [1 2].
534 Elements and 302 Nodes found.
ElectrodeNodes: [0 1 2 3 4 5 6 7]
GndNode: 8


array([[ 0.00339063,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.00343123,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.00329807, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.00699863,
        -0.00071779, -0.00154543],
       [ 0.        ,  0.        ,  0.        , ..., -0.00071779,
         0.00706994, -0.00118858],
       [ 0.        ,  0.        ,  0.        , ..., -0.00154543,
        -0.00118858,  0.00731521]], shape=(302, 302))